[package]
name = "data_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
google-sheets4 = "4.0.1"
hyper = "0.14.24"
hyper-rustls = "0.23.2"
