Table "users" {
  "id" BIGINT [pk, increment]
  "name" VARCHAR(255)
  "email" VARCHAR(255) [unique]
  "email_verified_at" TIMESTAMP
  "PASSWORD" VARCHAR(255)
  "remember_token" VARCHAR(100)
  "created_at" TIMESTAMP
  "updated_at" TIMESTAMP
}

Table "password_resets" {
  "email" VARCHAR(255) [pk]
  "token" VARCHAR(255)
  "created_at" TIMESTAMP
}

Table "failed_jobs" {
  "id" BIGINT [pk, increment]
  "uuid" VARCHAR(255) [unique]
  "connection" TEXT
  "queue" TEXT
  "payload" LONGTEXT
  "exception" LONGTEXT
  "failed_at" TIMESTAMP [default: `CURRENT_TIMESTAMP`]
}

Table "products" {
  "id" BIGINT [pk, increment]
  "product_code" VARCHAR(255) [unique]
  "name" VARCHAR(255)
  "category" VARCHAR(255)
  "stock" INT
  "unit_price" VARCHAR(255)
  "sales_unit_price" VARCHAR(255)
  "created_at" TIMESTAMP
  "updated_at" TIMESTAMP
}

Table "customers" {
  "id" BIGINT [pk, increment]
  "name" VARCHAR(255)
  "email" VARCHAR(255) [unique]
  "company" VARCHAR(255)
  "address" VARCHAR(255)
  "phone" VARCHAR(255)
  "created_at" TIMESTAMP
  "updated_at" TIMESTAMP
}

Table "orders" {
  "id" BIGINT [pk, increment]
  "email" VARCHAR(255)
  "product_code" VARCHAR(255)
  "product_name" VARCHAR(255)
  "quantity" INT
  "order_status" INT
  "created_at" TIMESTAMP
  "updated_at" TIMESTAMP
}

Table "invoices" {
  "id" BIGINT [pk, increment]
  "customer_name" VARCHAR(255)
  "customer_mail" VARCHAR(255)
  "company" VARCHAR(255)
  "address" VARCHAR(255)
  "item" VARCHAR(255)
  "product_name" VARCHAR(255)
  "price" VARCHAR(255)
  "quantity" INT
  "total" VARCHAR(255)
  "payment" VARCHAR(255)
  "due" VARCHAR(255)
  "created_at" TIMESTAMP
  "updated_at" TIMESTAMP
}
